services:
  beerlog:
    container_name: ${PROJECT_NAME}
    image: ${PROJECT_NAME}
    user: ${PROJECT_NAME}
    hostname: docker
    working_dir: ${WORK_DIR}
    ports:
      - ${PORT}:${PORT}
    entrypoint: ["poetry", "run"]
    command: ["beerlog_api"]
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
      target: development
      args:
        PROJECT_NAME: ${PROJECT_NAME}
        WORK_DIR: ${WORK_DIR}
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    volumes:
      - type: bind
        source: ./
        target: ${WORK_DIR}/
      - ${WORK_DIR}/.venv
