services:
  beerlog-database:
    container_name: ${BEERLOG_DATABASE_NAME}
    image: postgres:14.4
    environment:
      - POSTGRES_USER=${BEERLOG_PROJECT_NAME}
      - POSTGRES_PASSWORD=${BEERLOG_PROJECT_NAME}
      - POSTGRES_DB=${BEERLOG_DATABASE_NAME}
    ports:
      - ${BEERLOG_DATABASE_PORT}:${BEERLOG_DATABASE_PORT}

  beerlog:
    depends_on:
      - beerlog-database
    container_name: ${BEERLOG_PROJECT_NAME}
    image: ${BEERLOG_PROJECT_NAME}
    user: ${BEERLOG_PROJECT_NAME}
    hostname: docker
    working_dir: ${BEERLOG_WORK_DIR}
    ports:
      - ${BEERLOG_API_PORT}:${BEERLOG_API_PORT}
    entrypoint: ["poetry", "run"]
    command: ["beerlog_api"]
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
      target: development
      args:
        PROJECT_NAME: ${BEERLOG_PROJECT_NAME}
        WORK_DIR: ${BEERLOG_WORK_DIR}
        USER_ID: ${BEERLOG_USER_ID}
        GROUP_ID: ${BEERLOG_GROUP_ID}
    volumes:
      - type: bind
        source: ./
        target: ${BEERLOG_WORK_DIR}/
      - ${BEERLOG_WORK_DIR}/.venv
