name: Continuos Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  python-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.8"
          cache: "pip"
          cache-dependency-path: "requirements/*.txt"

      - name: Install Python dependencies
        run: |
          pip install -r requirements/prod.txt
          pip install -r requirements/dev.txt

      - name: Python test and coverage
        run: pytest

      - name: Save html coverage report
        uses: actions/upload-artifact@v2
        with:
          name: html-coverage-report
          path: tests/coverage-results/htmlcov/

      - name: Python type check
        run: mypy .

      - name: Python linter
        run: prospector

      - name: Code format
        run: |
          isort --check --diff .
          black --check --diff .
          ec -verbose

      - name: Security vulnerability scan
        run: |
          bandit --recursive beerlog
          safety check --file requirements/prod.txt --full-report
          safety check --file requirements/dev.txt --full-report

      - name: Test documentation
        run: |
          sphinx-apidoc --module-first --private --output-dir docs/modules beerlog
          sphinx-build -W -T -v -n docs public

  docker-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hadolint/hadolint-action@v2.0.0
        with:
          dockerfile: docker/Dockerfile
